# syntax=docker/dockerfile:1
ARG BASE_IMAGE=quay.io/pypa/manylinux2014_x86_64
FROM ${BASE_IMAGE}

ARG OPENSSL_TARGET=linux-x86_64
ARG OPENSSL_VERSION=3.5.8
ARG LIBRETLS_VERSION=3.8.1
ARG ZSTD_VERSION=1.5.7

ENV OPENSSL_TARGET=${OPENSSL_TARGET}
ENV OPENSSL_VERSION=${OPENSSL_VERSION}
ENV LIBRETLS_VERSION=${LIBRETLS_VERSION}
ENV ZSTD_VERSION=${ZSTD_VERSION}
ENV STATIC_PREFIX=/opt/static

COPY build.sh /usr/local/bin/build.sh
RUN chmod +x /usr/local/bin/build.sh && /usr/local/bin/build.sh

ENV PATH="/opt/rh/devtoolset-10/root/usr/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:${LD_LIBRARY_PATH}"
ENV PKG_CONFIG_PATH="${STATIC_PREFIX}/lib/pkgconfig:${STATIC_PREFIX}/lib64/pkgconfig"
ENV CPATH="${STATIC_PREFIX}/include"
ENV LIBRARY_PATH="${STATIC_PREFIX}/lib:${STATIC_PREFIX}/lib64"

WORKDIR /work